eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:900/eureka/
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 49
# spring:
#   application:
#     name: UserServices678897
# spring:
#   application:
#     name: default-name
